apiVersion: v1
kind: Service
metadata:
  name: flask-basic-k8s-service
spec:
  type: NodePort
  selector:
    app: flask-basic-k8s
  ports:
      - nodePort: 31000
        protocol: TCP
        port: 8080